//
// Created by temTeng on 2021/7/8.
//

#ifndef DATASTRUCTUREANDALGORITHM_EIGHTQUEENSPUZZLETEST_H
#define DATASTRUCTUREANDALGORITHM_EIGHTQUEENSPUZZLETEST_H

void EightQueensPuzzleTest();

#endif //DATASTRUCTUREANDALGORITHM_EIGHTQUEENSPUZZLETEST_H
