//
// Created by temTeng on 2021/7/8.
//

#ifndef DATASTRUCTUREANDALGORITHM_MAGICCARDSSINGLELINKEDCIRCULARLISTTEST_H
#define DATASTRUCTUREANDALGORITHM_MAGICCARDSSINGLELINKEDCIRCULARLISTTEST_H

void MagicCardsSingleLinkedCircularListTest();

#endif //DATASTRUCTUREANDALGORITHM_MAGICCARDSSINGLELINKEDCIRCULARLISTTEST_H
