//
// Created by temTeng on 2021/7/7.
//

#ifndef DATASTRUCTUREANDALGORITHM_LATINSQUARESINGLELINKEDCIRCULARLIST_H
#define DATASTRUCTUREANDALGORITHM_LATINSQUARESINGLELINKEDCIRCULARLIST_H
void LatinSquareSingleLinkedCircularList();
#endif //DATASTRUCTUREANDALGORITHM_LATINSQUARESINGLELINKEDCIRCULARLIST_H
