//
// Created by temTeng on 2021/7/7.
//

#ifndef DATASTRUCTUREANDALGORITHM_SEQUENCESTACKTEST_H
#define DATASTRUCTUREANDALGORITHM_SEQUENCESTACKTEST_H
void SequenceStackTest();
#endif //DATASTRUCTUREANDALGORITHM_SEQUENCESTACKTEST_H
