//
// Created by temTeng on 2021/7/8.
//

#ifndef DATASTRUCTUREANDALGORITHM_SUBSTRINGSEARCHTEST_H
#define DATASTRUCTUREANDALGORITHM_SUBSTRINGSEARCHTEST_H

void SubstringSearchTest();

void partialMatchTableTest();

#endif //DATASTRUCTUREANDALGORITHM_SUBSTRINGSEARCHTEST_H
