//
// Created by temTeng on 2021/7/8.
//

#ifndef DATASTRUCTUREANDALGORITHM_BRUTEFORCESUBSTRINGSEARCH_H
#define DATASTRUCTUREANDALGORITHM_BRUTEFORCESUBSTRINGSEARCH_H


int bruteForceSubstringSearch(char text[], char pattern[]);

#endif //DATASTRUCTUREANDALGORITHM_BRUTEFORCESUBSTRINGSEARCH_H
