//
// Created by temTeng on 2021/7/7.
//

#ifndef DATASTRUCTUREANDALGORITHM_MAGICCARDS_H
#define DATASTRUCTUREANDALGORITHM_MAGICCARDS_H

void MagicCards();

#endif //DATASTRUCTUREANDALGORITHM_MAGICCARDS_H
