//
// Created by temTeng on 2021/7/7.
//

#ifndef DATASTRUCTUREANDALGORITHM_MAGICCARDSSINGLELINKEDCIRCULARLIST_H
#define DATASTRUCTUREANDALGORITHM_MAGICCARDSSINGLELINKEDCIRCULARLIST_H

void MagicCardsSingleLinkedCircularList();

#endif //DATASTRUCTUREANDALGORITHM_MAGICCARDSSINGLELINKEDCIRCULARLIST_H
